ENVIRONMENT: production
SERVER:
  HOST: "localhost:8080"
DB:
  PATH: "data/dvarapala.db"
LOG:
  DIR: "log"
AUTH:
  JWT_SECRET: "a-very-secure-and-shared-secret-key"
CORS:
  ALLOWED_ORIGINS:
    - "*"
